### ISSUE TITLE
Merge with original repo's beta branch changes

### ISSUE THREAD

**Issue by jmhurst1** [smdupor/expertiza#13]
We should merge with https://github.com/expertiza/expertiza beta branch and ensure that there are no conflicts and ensure functionality.

**Comment by smdupor** [comment]
I merged in the latest from expertiza/beta yesterday and troubleshot/fixed the build issues so build is running clean again. Do we want to leave this issue open or is it OK to close since this will be a continuous process as builds are run after each new commit?
