### ISSUE TITLE
Create RSpec Feature Tests

### ISSUE THREAD

**Issue by jmhurst1** [smdupor/expertiza#21]
Need to create RSpec Feature Tests for new functionality.

Current feature tests are in expertiza\spec\features.

**Comment by smdupor** [comment]
Commenting with my notes on the interactive testable features I need to write tests for, and anticipate working on in the next few days (all on view_team.html.erb):
* show/hide button is gone. header onClick will expand/collapse the heatgrid just like the other tables on the page.
* header onClick to expand/collapse must work
* heatgrid and any notes or buttons should not be shown at all on page if no tags available for this assignment.
* at page onload, heatgrid should render open (not collapsed) if any tags are not done, and render collapsed if all are done.
